export const artists = [
  {
    id: 1,
    name: "Imagine Dragons",
    genre: "Alternative/Pop Rock",
    image: "/imagine-dragons.jpg",
  },
  {
    id: 2,
    name: "Lorde",
    genre: "Pop",
    image: "/lorde.jpg",
  },
  {
    id: 3,
    name: "The Weeknd",
    genre: "R&B/Pop",
    image: "/the-weeknd.jpg",
  },
  {
    id: 4,
    name: "Florence + The Machine",
    genre: "Indie Rock",
    image: "/florence-machine.jpg",
  },
  {
    id: 5,
    name: "Tame Impala",
    genre: "Psychedelic Rock",
    image: "/tame-impala.jpg",
  },
  {
    id: 6,
    name: "Mumford & Sons",
    genre: "Folk Rock",
    image: "/mumford-sons.jpg",
  },
]

export const concerts = [
  {
    id: 1,
    artist: "Imagine Dragons",
    venue: "The Metro",
    city: "Chicago",
    date: "March 15, 2026",
    price: 55,
    coordinates: [41.9486, -87.6556],
  },
  {
    id: 2,
    artist: "Lorde",
    venue: "Brooklyn Steel",
    city: "New York",
    date: "March 22, 2026",
    price: 50,
    coordinates: [40.7128, -73.9352],
  },
  {
    id: 3,
    artist: "The Weeknd",
    venue: "The Wiltern",
    city: "Los Angeles",
    date: "April 3, 2026",
    price: 65,
    coordinates: [34.0621, -118.3098],
  },
  {
    id: 4,
    artist: "Florence + The Machine",
    venue: "Troubadour",
    city: "West Hollywood",
    date: "April 10, 2026",
    price: 60,
    coordinates: [34.09, -118.385],
  },
  {
    id: 5,
    artist: "Tame Impala",
    venue: "House of Blues",
    city: "Boston",
    date: "April 18, 2026",
    price: 55,
    coordinates: [42.3478, -71.0466],
  },
  {
    id: 6,
    artist: "Mumford & Sons",
    venue: "Blue Note",
    city: "New York",
    date: "April 25, 2026",
    price: 45,
    coordinates: [40.7295, -73.9965],
  },
  {
    id: 7,
    artist: "Imagine Dragons",
    venue: "The Fillmore",
    city: "San Francisco",
    date: "May 2, 2026",
    price: 58,
    coordinates: [37.7833, -122.433],
  },
  {
    id: 8,
    artist: "The Weeknd",
    venue: "Red Rocks",
    city: "Denver",
    date: "May 12, 2026",
    price: 75,
    coordinates: [39.6653, -105.2054],
  },
]
